name: miscelaneos
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_compass: ^0.8.0
  flutter_riverpod: ^2.4.5
  go_router: ^13.0.1
  google_fonts: ^6.1.0
  permission_handler: ^11.0.1
  riverpod_annotation: ^2.3.0
  sensors_plus: ^4.0.2

dev_dependencies:
  build_runner: ^2.4.6
  custom_lint: ^0.5.6
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
  riverpod_generator: ^2.3.5
  riverpod_lint: ^2.3.3

flutter:
  uses-material-design: true

  assets:
    - assets/images/compass/
